### PR TITLE
Remove misleading word "or" before snapshot date

### PR DESCRIPTION
**Pull request by jonico**
* remove misleading, superfluous "or" before snapshot date

### CODE REVIEW

**Comment by christian555555** [comment]
😎Arschloch  He He Dumme sau

Am Fr., 14. Feb. 2020 um 07:10 Uhr schrieb Marc Auberer <
notifications@github.com>:

**Comment by marcauberer** [comment]
Reported this abuse above

**Comment by jonico** [comment]
@rezendi: friendly bump to look into this PR

**Comment by rezendi** [comment]
Contextual syntactic blindness is fascinating, it took me a long time to see the "or" even with the changed paragraph highlighted! Thanks for this --

**Pull request merged**
