### PR TITLE
Added Tagalog/Filipino Translation

### PR DESCRIPTION
**Pull request by jcwebhole**

### CODE REVIEW

**Comment by rezendi** [comment]
"Thanks for the PR. We very much appreciate your work, but at least at the moment, we're limiting the translations of the Guide to professional translations. We may well revisit this in future and move to a more expansive list of crowdsourced translations, however, in which case this PR will be reopened and reexamined."

**Comment by rezendi** [comment]
Reopening to add to community guides.

**Comment by rezendi** [comment]
Will be happy to add this to the community guides if/when translation is complete - thanks!

**Comment by jcwebhole** [comment]
Thanks @rezendi what do you think should complete this request?

**Comment by rezendi** [comment]
Everything from line 229 onwards is still in English...

**Comment by jcwebhole** [comment]
revisited old repositories to clean up, I finished the translation as told

**Pull request merged**
