### PR TITLE
Website not Web Site

### PR DESCRIPTION
**Pull request by ucalyptus**
- [x] Docfix
cc: @rezendi

### CODE REVIEW

**Comment by Harmon758** [comment]
Why are you mentioning me?

**Comment by ucalyptus** [comment]
You have push access too I concur.

**Comment by Harmon758** [comment]
I'm not sure who or what you're concurring with, but I do not.

**Comment by ucalyptus** [comment]
ok

**Comment by rezendi** [comment]
Formal usage is arguably still generally "web site"; it is at least a thing for which multiple viable variations exist.

**Pull request closed without merging**
